name: voicepres
description: Voice Prescription.

version: 1.0.0+1

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  speech_to_text: ^2.1.0
#  path_provider: ^1.6.8
#  googleapis: ^0.55.0
#  googleapis_beta: ^0.50.0
  # For UI
  provider: 3.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:

sources:
flutter:

  uses-material-design: true
